// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrj3vDZfM1Ls6lSKRHZAY4D520dMcvRPc',
    appId: '1:342056390141:web:09c7685014a2fed8799d94',
    messagingSenderId: '342056390141',
    projectId: 'gestione-soldi-33c01',
    authDomain: 'gestione-soldi-33c01.firebaseapp.com',
    storageBucket: 'gestione-soldi-33c01.firebasestorage.app',
    measurementId: 'G-YKD3LYRTE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvfzYpJ7DZ7oVRaoN_Lwz7UsObQZ3YB4',
    appId: '1:342056390141:android:a932a4c729f31088799d94',
    messagingSenderId: '342056390141',
    projectId: 'gestione-soldi-33c01',
    storageBucket: 'gestione-soldi-33c01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuWh-9rBra9rwmmdnLrb6hOFcKkYJsCa0',
    appId: '1:342056390141:ios:d0742eb9215d7941799d94',
    messagingSenderId: '342056390141',
    projectId: 'gestione-soldi-33c01',
    storageBucket: 'gestione-soldi-33c01.firebasestorage.app',
    iosBundleId: 'com.example.gestionaleSoldi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuWh-9rBra9rwmmdnLrb6hOFcKkYJsCa0',
    appId: '1:342056390141:ios:d0742eb9215d7941799d94',
    messagingSenderId: '342056390141',
    projectId: 'gestione-soldi-33c01',
    storageBucket: 'gestione-soldi-33c01.firebasestorage.app',
    iosBundleId: 'com.example.gestionaleSoldi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrj3vDZfM1Ls6lSKRHZAY4D520dMcvRPc',
    appId: '1:342056390141:web:f0bd862f0eb9dea2799d94',
    messagingSenderId: '342056390141',
    projectId: 'gestione-soldi-33c01',
    authDomain: 'gestione-soldi-33c01.firebaseapp.com',
    storageBucket: 'gestione-soldi-33c01.firebasestorage.app',
    measurementId: 'G-NMVNMV7R4C',
  );
}
